# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  run-gateway:
      desc: Run API GATEWAY
      cmds:
          - cd api-gateway && go run cmd/gateway/main.go

  dev-gateway:
      desc: Run API GATEWAY
      cmds:
          - cd api-gateway && air

  run-service-user:
    desc: Run User service
    cmds:
      - echo "{{.GREETING}}"
      - cd services/users && go run .

  dev-service-user:
      desc: Run User service dev
      cmds:
          - cd services/users && air

  run-service-kitchen:
    desc: Run Kitchen service
    cmds:
      - cd services/kitchen && go run .

  dev-service-kitchen:
    desc: Run Kitchen service dev
    cmds:
      - cd services/kitchen && air
