addr: ":8082"

mongo:
  uri: "mongodb://localhost:27017"
  db: "p22194"

jwt:
  secret: "hehe"            # keep empty if using env USERS_JWT_SECRET
  access_ttl: "15m"
  refresh_ttl: "168h"

log:
  level: "info"
  format: "pretty"